### ISSUE TITLE
Cannot override default application variables

### ISSUE THREAD

**Issue by jmaupetit** [openfun/arnold#100]
## Purpose

Latest changes in #99 introduced a regression making default application override impossible.

## Proposal

Load default application variables only if they are not already defined, _e.g._

```yaml
# apps/edxapp/vars/all/main.yml
defaults:
  edxapp_cms_host: "cms.{{ project_name}}.{{ domain_name }}"
  # ...

# iterate over defaults
# check if var is defined
# define it with default if not
```
