### ISSUE TITLE
Consider service templates whitelisting

### ISSUE THREAD

**Issue by jmaupetit** [openfun/arnold#128]
## Purpose

At the time if writing, Arnold auto-discovers service templates for an application. This is really useful to avoid having to declare explicitly every service template we will use. The counterpart is that it's not that obvious to inactivate some templates in particular conditions (environment, customer, etc.). Using a global conditional block in a jinja templates is not explicit and cannot be our answer to a missing configuration.

## Proposal

Similarly to `ConfigMap`s, we must be able to declare them.

```yaml
# group_vars/customer/patient0/development/main.yml

apps:
  - name: richie
  - name: edxapp
    services:
      - name: cms
        templates:
          - apps/edxapp/templates/cms/bc.yml.j2
          - apps/edxapp/templates/cms/dc_queue_default_priority.yml.j2
          - apps/edxapp/templates/cms/dc_queue_high_priority.yml.j2
          - apps/edxapp/templates/cms/dc_queue_low_priority.yml.j2
          - apps/edxapp/templates/cms/dc.yml.j2
          - apps/edxapp/templates/cms/is.yml.j2
          - apps/edxapp/templates/cms/job_01_collectstatic.yml.j2
          - apps/edxapp/templates/cms/job_04_db_migrate.yml.j2
          - apps/edxapp/templates/cms/job_05_load_fixtures.yml.j2
          - apps/edxapp/templates/cms/svc.yml.j2
        configs:
          - group_vars/customer/patient0/development/configs/edxapp/cms/docker_run.py.j2
          - group_vars/customer/patient0/development/configs/edxapp/cms/settings.yml.j2
      - name: lms
        configs:
          - group_vars/customer/patient0/development/configs/edxapp/lms/docker_run.py.j2
          - group_vars/customer/patient0/development/configs/edxapp/lms/settings.yml.j2
  - name: redis
```

**Comment by jmaupetit** [comment]
Instead of forcing every templates declaration, we can only add what needs to be override or extended based on the file name, _e.g._:

```yaml
apps:
  - name: edxapp
    services:
      - name: cms
        templates:
          # This template exists, it will be override
          - group_vars/customer/eugene/development/apps/edxapp/templates/cms/bc.yml.j2
          # This template does not exists, it will be added
          - group_vars/customer/eugene/development/apps/edxapp/templates/cms/job_08_foo.yml.j2
```
