### ISSUE TITLE
Better normalize and enforce our database names

### ISSUE THREAD

**Issue by sampaccoud** [openfun/arnold#153]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
We need to normalize and enforce database names because MySQL limits db names to **16 characters** by default.

**Describe the solution you'd like**
Name databases with a pattern: `{{ env_type }}-{{ customer }}-{{ app.name }}[{{ extra }}]`
where:

- `customer` is max 6 characters
- `env_type` is 1 character (because we are limited to 16 characters, we do not use 2 characters for this information):
    * `s`: staging
    * `t`: pre-production (after s... try/test...)
    * `p`: production
- `app.name` is limited to 6 characters: _e.g._ `richie`, `marsha`, `edxapp`, etc.
- `extra` is 1 character that can be added if we have several databases for a given customer/env_type/database.

This normalization will allow us to generate interface documents to automate the creation of all our databases. We propose the following format for this document:

```yaml
postgresql:
  9_10:
    # Richie staging for customer foo
    - name: s_foo_richie
      user: s_foo_richie
      password: 123456
    # Richie production for customer foo
    - name: p_foo_richie
      user: p_foo_richie
      password: 123456
    # Richie staging for customer bar
    - name: p_bar_richie
      user: p_bar_richie
      password: 123456
    # Marsha preproduction for customer bar
    - name: t_bar_marsha
      user: t_bar_marsha
      password: 123456
mysql:
  5_6:
    # Mysql production for customer foo
    - name: p_foo_edx
      user: p_foo_edx
      password: 123456
mongodb:
  3_0:
    # Mongodb production for customer foo on Mongodb 3.0
    - name: p_foo_edx
      user: p_foo_edx
      password: 123456
  3_2:
    # Mongodb production for customer bar on Mongodb 3.2
    - name: p_bar_edx
      user: p_bar_edx
      password: 123456
```

We must:

- [ ] modify our template and variables,
- [ ] add checks to enforce this pattern,
- [ ] generate interface vault files from which we can automate creation of these databases.

**Describe alternatives you've considered**
We hesitated with a pattern `{{ customer ]}-{{ env_type }}-{{ app}}` but:

- the project_name is  `{{ env_type }}-{{ customer }}`,
- since we shorten the `env_type` name, I would argue that `p-client-marsha` is nicer than `client-p-marsha`,
- `env_type` is the first differentiator (e.g production is usually a whole separate infrastructure).

**Comment by jmaupetit** [comment]
Instead of using barely readable keys for database engine version, what about using explicit fields to describe it:

```yaml
postgresql:
  - release: "9.10"
    databases:
      # Richie staging for customer foo
      - name: "s_foo_richie"
        user: "s_foo_richie"
        password: 123456
      # Richie production for customer foo
      - name: "p_foo_richie"
        user: "p_foo_richie"
        password: 123456
      # Richie staging for customer bar
      - name: "p_bar_richie"
        user: "p_bar_richie"
        password: 123456
      # Marsha preproduction for customer bar
      - name: "t_bar_marsha"
        user: "t_bar_marsha"
        password: 123456
mysql:
  - release: "5.6"
    databases:
      # Mysql production for customer foo
      - name: "p_foo_edx"
        user: "p_foo_edx"
        password: 123456
mongodb:
  - release: "3.0"
    databases:
      # Mongodb production for customer foo on Mongodb 3.0
      - name: "p_foo_edx"
        user: "p_foo_edx"
        password: 123456
  - release: "3.2"
    databases:
      # Mongodb production for customer bar on Mongodb 3.2
      - name: "p_bar_edx"
        user: "p_bar_edx"
        password: 123456
```

**Comment by jmaupetit** [comment]
After discussion with @lunika, our conclusions follow:

1. This `databases.vault.yml` should be located as any secret in `groups_vars/customer/{{ customer }}/{{ env_type }}/secrets/`.
2. Hence, this file can only define databases credentials for a particular customer in its environment.
3. We need to add an `application` field to database definition to perform generic JSON queries in vault templates.

A complete example for customer `foo` in `staging` follows:

```yaml
# groups_vars/customer/foo/staging/secrets/databases.vault.yml
postgresql:
  - release: "9.10"
    databases:
      # Richie staging for customer foo
      - application: "richie"
        name: "s_foo_richie"
        user: "s_foo_richie"
        password: 123456

      # Marsha staging for customer foo
      - application: "marsha"
        name: "s_foo_marsha"
        user: "s_foo_marsha"
        password: 123456

mysql:
  - release: "5.6"
    databases:
      # Mysql staging for customer foo
      - application: "edxapp"
        name: "s_foo_edx"
        user: "s_foo_edx"
        password: 123456

mongodb:
  - release: "3.2"
    databases:
      # Mongodb staging for customer foo on Mongodb 3.2
      - application: "edxapp"
        name: "s_foo_edx"
        user: "s_foo_edx"
        password: 123456

      - application: "forum"
        name: "s_foo_forum"
        user: "s_foo_forum"
        password: 123456
```

**Comment by sampaccoud** [comment]
@jmaupetit call it "app" to be coherent with the rest of the code?

**Comment by jmaupetit** [comment]
:thinking: not sure: this is structured data and all fields are explicit with their complete name. WDYT?

**Comment by sampaccoud** [comment]
not sure either but I do find it confusing that the application folder is called `apps` and everywhere we use `app`. It would seem like it's some different information...

**Comment by lunika** [comment]
> MySQL limits db names to 16 characters by default.

This is not true anymore since version `5.7`. The limit is now 32 characters and in arnold this is the version we use.

**Comment by lunika** [comment]
To implement this feature this is what I plan to do:

First we have to describe the databases we need for each application. To do this a file can be created in `apps/{app}/vars` and will be called `databases.yml`.
The content of this file can be the following example:

```
databases:
  - type: "mysql"
    release: "5.7"
  - type: "mongodb"
    release: "3.2"
```

Once all files created the playbook should to the tasks described below:
- load databases vault if existing and load its variables
- loop on all `apps`
- for each app, check if the database file exists
- load it if true
- loop on every databases described
- check if the database is already described in database vaul
- if no add it.
- output the database vault variable in a template.

Here I don't know if I can do all of this only with ansible, if it's easy to manipulate a variable and modify it easily in a task.

WDYT @jmaupetit ?

- compute

**Comment by jmaupetit** [comment]
This exactly what I had in mind. It's sometimes a bit tricky to manipulate variables in Ansible, but we can write custom filters to ease our life if required (:snake: FTW).

Concerning, the `databases.yml` file I would suggest to name the `type` key `engine`:

```yaml
# apps/{{ app.name }}/vars/databases.yml
databases:
  - engine: "mysql"
    release: "5.7"
  - engine: "mongodb"
    release: "3.2"
```

**Comment by lunika** [comment]
And shouldn't be easier to keep the structure suggested by @sampaccoud ? Having the database version as a key is a think a lot easier for us to build this structure. So we would have:

```yaml
# groups_vars/customer/foo/staging/secrets/databases.vault.yml
postgresql:
  9.10:
    # Richie staging for customer foo
    - application: "richie"
      name: "s_foo_richie"
      user: "s_foo_richie"
      password: 123456

    # Marsha staging for customer foo
    - application: "marsha"
      name: "s_foo_marsha"
      user: "s_foo_marsha"
      password: 123456

mysql:
  5.6:
    # Mysql staging for customer foo
    - application: "edxapp"
      name: "s_foo_edx"
      user: "s_foo_edx"
      password: 123456

mongodb:
  3.2:
    # Mongodb staging for customer foo on Mongodb 3.2
    - application: "edxapp"
      name: "s_foo_edx"
      user: "s_foo_edx"
      password: 123456

    - application: "forum"
      name: "s_foo_forum"
      user: "s_foo_forum"
      password: 123456
```

keys like `9.6` looks like valid, I tested them in a linter and it didn't warns me

**Comment by jmaupetit** [comment]
What I dislike is that it's not self-describing structured data. This choice should not be driven by implementation details.

**Comment by lunika** [comment]
We should also maybe wrap all this structure in a main key `databases` ?

```yaml
# groups_vars/customer/foo/staging/secrets/databases.vault.yml
databases:
  postgresql:
    - release: "9.10"
      databases:
        # Richie staging for customer foo
        - application: "richie"
          name: "s_foo_richie"
          user: "s_foo_richie"
          password: 123456

        # Marsha staging for customer foo
        - application: "marsha"
          name: "s_foo_marsha"
          user: "s_foo_marsha"
          password: 123456

  mysql:
    - release: "5.6"
      databases:
        # Mysql staging for customer foo
        - application: "edxapp"
          name: "s_foo_edx"
          user: "s_foo_edx"
          password: 123456

  mongodb:
    - release: "3.2"
      databases:
        # Mongodb staging for customer foo on Mongodb 3.2
        - application: "edxapp"
          name: "s_foo_edx"
          user: "s_foo_edx"
          password: 123456

        - application: "forum"
          name: "s_foo_forum"
          user: "s_foo_forum"
          password: 123456 
```
