### ISSUE TITLE
Create databases playbook

### ISSUE THREAD

**Issue by lunika** [openfun/arnold#198]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**

We would like to have a playbook to create databases when they live outside OpenShift. Once the databases vault is generated, this playbook will read the previously created vault and then create all the databases described in this file.

**Describe the solution you'd like**

To be able to create the databases, we need to know some information that does not exist for now in Arnold:

- administrator account for database engine
- database engine host 

For this we will need a new configuration file describing what we need with something like this:

```yaml
credentials:
  mongodb:
    - release: 3.2
      login: john
      password: doe
      host: cluster.com
      port: 27017
  mysql:
    - release: 5.7
      login: john
      password: doe
      host: cluster.com
      port: 3306
  postgresql:
    - release: 9.6
      login: john
      password: doe
      host: cluster.com
      port: 5432
```

This structure is really similar to what is already present in `databases.vault.yml` file, so the existing `databases.vault.yml` structure can be merged with the one described before, we will have something like this:

```yaml
databases:
  mongodb:
  - databases:
    - application: forum
      name: d_eugene_forum
      password: xxxxxx
      user: d_eugene_forum
    - application: edxapp
      name: d_eugene_edxapp
      password: xxxxx
      user: d_eugene_edxapp
    release: '3.2'
    credentials:
      login: john
      password: doe
      host: cluster.com
      port: 27017
  mysql:
  - databases:
    - application: edxapp
      name: d_eugene_edxapp
      password: xxxxx
      user: d_eugene_edxapp
    release: '5.7'
    credentials:
      login: john
      password: doe
      host: cluster.com
      port: 3306
  postgresql:
  - databases:
    - application: marsha
      name: d_eugene_marsha
      password: xxxx
      user: d_eugene_marsha
    - application: richie
      name: d_eugene_richie
      password: xxxxx
      user: d_eugene_richie
    release: '9.6'
    credentials:
      login: john
      password: doe
      host: cluster.com
      port: 5432
```

I don't think creating this file can be automated and editing it manually is not really easy. But there is also an other problem, maybe (and in most cases it will be the case) the cluster will not be exposed to internet so it will be impossible to reach it like the way I described but by connecting to the server through ssh. So to delegate the Ansible task to an other solution.

The more I'm looking for a solution, the more I think it can't be a generic playbook because there is so many way to connect to the database and create the user and database.
