### ISSUE TITLE
Skip set_vars in a playbook if apps is already defined

### ISSUE THREAD

**Issue by jmaupetit** [openfun/arnold#254]
## Purpose

Almost every playbook loads the `set_vars` tasks list even if all apps have already been defined. This is time/resource consuming when running meta-playbooks, and it pollutes our logs. Let's avoid this!

## Proposal

Import the `set_vars.yml` tasks only when `apps` is not defined, in every playbook.

```yaml
- hosts: local
  gather_facts: False

  tasks:
    - import_tasks: tasks/set_vars.yml
      when: apps is not defined
```
