### ISSUE TITLE
Add tray version support

### ISSUE THREAD

**Issue by jmaupetit** [openfun/arnold#308]
## Purpose

While fetching an application tray, we need to support multiple versions of the tray.

## Proposal

- [ ] update the apps tree to something like: 

`apps/{{ tray.name }}/{{ tray.version }}/templates/...`

- [ ] add versions to active apps, _e.g._:

```yaml
apps:
  - name: richie
    version: 1.0.0
```
- [ ] collect apps given this version

Optional:

- [ ] add default version support
