### ISSUE TITLE
Add support for multiple host per-service

### ISSUE THREAD

**Issue by jmaupetit** [openfun/arnold#90]
## Purpose

We currently only support one host per service definition to create underlying routes. As some apps (like `edxapp`) may have many routes pointing to the same service (_e.g._ nginx), we need to improve hosts management.

## Proposal

Move the `app.service.host` type from a simple string to a list of dictionaries with the route, the targeted service name and the targeted port.

**Comment by sampaccoud** [comment]
Actually, we should also consider leaving it like this... You wanted to declare a separate service for fonzie so it makes sense if lms and cms are separate services... WDYT?

**Comment by jmaupetit** [comment]
`cms`, `lms` and `fonzie` will still be separated services, but the `nginx` service must support serving those three services (3 hosts with their own URL).

To be perfectly clear about the actual and the future `apps` var structure, a more concrete explanation follows. The current `apps` definition for development is:

```yaml
# group_vars/env_type/development.yml
apps:
  - name: richie
    services:
      - name: nginx
        host: "{{ richie_host }}"
        port: "{{ richie_nginx_port }}"
  - name: edxapp
    services:
      - name: nginx
        host: "{{ edxapp_cms_host }}"
        port: "{{ edxapp_nginx_cms_port }}"
```

By doing, so we are not able to define multiple `host`s for the `nginx` service. Hence we need to move to something like:

```yaml
apps:
  - name: richie
    services:
      - name: nginx
        routes:
          - host: "{{ richie_host }}"
            port: "{{ richie_nginx_port }}"
  - name: edxapp
    services:
      - name: nginx
        routes:
          - host: "{{ edxapp_cms_host }}"
            port: "{{ edxapp_nginx_cms_port }}"
          - host: "{{ edxapp_lms_host }}"
            port: "{{ edxapp_nginx_lms_port }}"
```

Is that more clear?
